added Profile Page
UCSDTESC/tesc-events-ui pull request #10
Opened 2023-02-01 00:52 UTC by Jasonnyang

Added profile page component

2023-02-09 05:35 UTC, shanekim28 requested changes
Great start! Left some change requests for the bigger stuff I noticed. Anything with "Nit" is optional but highly recommended to look into.

2023-02-09 05:35 UTC, shanekim28 commented on src/assets/css/ProfilePage.css
> +    width: 390px;
```suggestion
    width: 50%;
```

2023-02-09 05:35 UTC, shanekim28 commented on src/assets/css/ProfilePage.css
> +    margin-left: 41%;
This feels pretty dirty; usually we want to keep numbers like these in a way that can be expressed with rational numbers (like 25% = 1/4, 33% = 1/3, etc.). There's probably a much better way to center this.

2023-02-09 05:35 UTC, shanekim28 commented on src/assets/css/ProfilePage.css
> +.some-page-wrapper {
Nit: class names should be clear in their function

2023-02-09 05:35 UTC, shanekim28 commented on src/assets/css/ProfilePage.css
> +.column{
Nit: This class is technically a container, consider changing the name to something that reflects this

2023-02-09 05:35 UTC, shanekim28 commented on src/assets/css/ProfilePage.css
> +.second-text {
Nit: consider naming this class something clearer

2023-02-09 05:35 UTC, shanekim28 commented on src/pages/ProfilePage.tsx
> +import ReactDOM from 'react-dom/client';
```suggestion
import React from 'react';
import ReactDOM from 'react-dom/client';
```
Remove unused imports

2023-02-09 05:35 UTC, shanekim28 commented on src/components/Sidebar.tsx
> +import ProfilePage from "../pages/ProfilePage";
```suggestion
import "../assets/css/Sidebar.css"
```
Apply sidebar styling to sidebar and remove unused imports

2023-02-09 05:35 UTC, shanekim28 commented on src/assets/css/ProfilePage.css
> +    border: 1px solid white;
```suggestion
    border: 1px solid white;  
```
Remove border

2023-02-09 05:35 UTC, shanekim28 commented on src/assets/css/ProfilePage.css
> +    border: 1px solid white;
```suggestion
    border: 1px solid white;
```
Remove border radius

2023-02-09 05:35 UTC, shanekim28 commented on src/pages/ProfilePage.tsx
> +                        <form>
Don't need all these form tags, you can use just one for all the input fields

2023-02-09 05:35 UTC, shanekim28 commented on src/pages/ProfilePage.tsx
> +                            <input type="text" placeholder="First Name" className="text-input" />
```suggestion
                            <input type="text" placeholder="First Name" className="text-input inset" />
```
Apply inset styling here and on all other inputs

2023-02-09 05:35 UTC, shanekim28 commented on src/pages/ProfilePage.tsx
> +                        <form>
Same here, just use one form tag

2023-02-09 05:35 UTC, shanekim28 commented on src/pages/ProfilePage.tsx
> +                        <form>
And here, just one form tag is good for all of these inputs. Apply inset class to all inputs as well

2023-03-02 20:13 UTC, Jasonnyang commented
Added new patch and get API functions and fixed the changes above

2023-04-17 17:00 UTC, merged